 version: 2.1

 jobs:
  run-unit-tests-and-build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1
    steps:
      - checkout
      - run: find .
      - run: dotnet restore
      - run: dotnet test
      - run: dotnet build

 workflows:
  build-and-deploy:
    jobs:
      - run-unit-tests-and-build:
          filters:
            branch:
              only: /(sprint\-\d+)/


